---
- name: Ensure tmux config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/tmux"
    state: directory
    mode: "0755"

- name: Clone tmux plugin manager (TPM)
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ ansible_env.HOME }}/.config/tmux/plugins/tpm"
    version: master
    update: true

- name: Copy tmux.conf
  copy:
    src: "{{ playbook_dir }}/../files/tmux/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.config/tmux/tmux.conf"
    mode: "0644"
