- name: Install Zsh
  include_tasks: zsh.yml

- name: Install Oh My Zsh
  include_tasks: omz.yml

- name: Install and configure Oh My Zsh plugins
  include_tasks: omz-plugin.yml

- name: Ensure zsh is the default shell for the login user
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true
