- name: Ensure curl is installed
  package:
    name: curl
    state: present


- name: Install k3s agent if not already installed
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -s -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s-agent service is running
  systemd:
    name: k3s-agent
    state: started
    enabled: yes
