---
- name: Load OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set timezone on Linux
  import_tasks: linux.yml
  when: ansible_system == "Linux"

- name: Set timezone on macOS
  import_tasks: darwin.yml
  when: ansible_system == "Darwin"
