---
- name: Cleanup all VMs
  hosts: vm_host
  become: true
  gather_facts: true
  roles:
    - vm_cleanup
  vars:
    ansible_become_password: "{{ ansible_password }}"

- name: VM proxy delete
  import_playbook: vm_proxy_delete.yml
