---
- name: Install VM host base packages
  hosts: vm_host
  become: true
  gather_facts: true
  roles:
    - role: base_packages
      vars:
        base_packages: "{{ vm_host_packages }}"
  vars:
    ansible_become_password: "{{ ansible_password }}"
