---
- name: Install VM host base packages
  hosts: vm_host
  become: true
  gather_facts: true
  roles:
    - role: base_packages
      vars:
        base_packages: "{{ vm_host_packages }}"
  vars:
    ansible_become_password: "{{ ansible_password }}"

- name: Ensure VM host prerequisites
  hosts: vm_host
  become: true
  gather_facts: true
  roles:
    - vm_check
  vars:
    ansible_become_password: "{{ ansible_password }}"

- name: Ensure VM bridge network
  hosts: vm_host
  become: true
  gather_facts: false
  roles:
    - vm_network
  vars:
    ansible_become_password: "{{ ansible_password }}"
