---
- name: Install neovim package (Fedora)
  dnf:
    name: "neovim"
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install neovim package on macOS
  tags: [neovim, brew]
  include_role:
    name: homebrew
  vars:
    homebrew_packages: "neovim"
  when: ansible_os_family == "Darwin"

- name: Install base packages on Debian-based systems
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

